"""Read-only SQL extractor that materializes market OHLC artifacts."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import pandas as pd

from data.sql.db_config import load_db_config
from trading_center.readonly_dashboard import REPO_ROOT, write_csv


METHOD_VERSION = "trading_center_sql_market_data_readonly_v1"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "artifacts/tfg/trading_center_sql_market_data_readonly_v1_2026-05-31"
DEFAULT_TIMEFRAMES = ("M15", "H1", "H4", "D1")
DEFAULT_GROUPS: tuple[str, ...] = ()
DEFAULT_BARS_PER_PAIR = 2000
LOCAL_HOSTS = {"localhost", "127.0.0.1", "::1"}
REQUIRED_OHLC_COLUMNS = [
    "market_group",
    "symbol",
    "timeframe",
    "timestamp",
    "open",
    "high",
    "low",
    "close",
    "tick_volume",
    "spread",
    "real_volume",
]
FORBIDDEN_SQL_TOKENS = re.compile(
    r"\b(insert|update|delete|drop|alter|create|truncate|replace|merge|grant|revoke|call|load|outfile|infile)\b",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class SqlMarketDataReadonlyConfig:
    """Configuration for one safe SQL market-data extraction."""
    output_dir: Path = DEFAULT_OUTPUT_DIR
    timeframes: tuple[str, ...] = DEFAULT_TIMEFRAMES
    groups: tuple[str, ...] = DEFAULT_GROUPS
    bars_per_pair: int = DEFAULT_BARS_PER_PAIR
    allow_nonlocal_db: bool = False


@dataclass(frozen=True)
class SqlMarketDataReadonlyResult:
    """Artifacts and audit tables generated by a read-only SQL extraction."""
    ohlc: pd.DataFrame
    source_coverage: pd.DataFrame
    query_audit: pd.DataFrame
    config_audit: pd.DataFrame
    safety_audit: pd.DataFrame
    issues_or_risks: pd.DataFrame
    run_meta: dict[str, Any]


ConnectionFactory = Callable[[dict[str, Any]], Any]


def extract_sql_market_data(
    config: SqlMarketDataReadonlyConfig | None = None,
    *,
    connection_factory: ConnectionFactory | None = None,
) -> SqlMarketDataReadonlyResult:
    """Extract local SQL OHLC data through SELECT-only guarded queries."""
    config = config or SqlMarketDataReadonlyConfig()
    generated_at = utc_now()
    db_config, config_source = load_db_config()
    config_audit = build_config_audit(db_config, config_source, config)
    symbols_query, symbols_params = build_enabled_symbols_query(config)
    pair_query = build_pair_ohlc_query()
    query_audit = build_query_audit(symbols_query, pair_query, symbols_params, config)
    safety = build_safety_audit(symbols_query, pair_query)

    issues: list[dict[str, Any]] = []
    ohlc = empty_ohlc_frame()
    db_connected = False
    sql_real_read = False
    query_error = ""

    if not is_local_host(str(db_config.get("host"))) and not config.allow_nonlocal_db:
        issues.append(
            issue(
                "R01",
                "high",
                "blocked",
                "DB host is not local, so the read-only extractor refused to connect.",
                "Use a local read-only DB target or pass allow_nonlocal_db only in a controlled future phase.",
            )
        )
    elif not (is_select_only_query(symbols_query) and is_select_only_query(pair_query)):
        issues.append(
            issue(
                "R02",
                "high",
                "blocked",
                "Generated query did not pass the SELECT-only guard.",
                "Keep this extractor limited to parametrized SELECT statements.",
            )
        )
    else:
        connection = None
        try:
            connection = (connection_factory or default_connection_factory)(db_config)
            db_connected = True
            ohlc = fetch_market_ohlc(connection, config)
            sql_real_read = True
        except Exception as exc:  # pragma: no cover - exercised via CLI environment.
            query_error = exc.__class__.__name__
            issues.append(
                issue(
                    "R03",
                    "medium",
                    "open",
                    "SQL read-only extraction could not complete.",
                    f"Check local DB availability and credentials outside the dashboard. Error class: {query_error}.",
                )
            )
        finally:
            close_connection(connection)

    ohlc = normalize_ohlc_frame(ohlc)
    coverage = source_coverage_audit(ohlc, config)
    if not issues:
        issues.append(
            issue(
                "R00",
                "low",
                "closed",
                "SQL read-only market extraction completed without blocking safety issues.",
                "Keep the extracted OHLC as an artifact input to the dashboard.",
            )
        )

    run_meta = {
        "phase": METHOD_VERSION,
        "generated_at": generated_at,
        "decision": decide_result(issues, ohlc),
        "sql_market_data_readonly_implemented": True,
        "sql_real_read": sql_real_read,
        "sql_real_written": False,
        "ddl_executed": False,
        "db_connected": db_connected,
        "mt5_connected": False,
        "telegram_connected": False,
        "orders_sent": 0,
        "signals_generated": False,
        "backtests_executed": False,
        "wavecount_used_as_filter": False,
        "timeframes": list(config.timeframes),
        "groups": list(config.groups),
        "bars_per_pair": int(config.bars_per_pair),
        "rows_read": int(len(ohlc)),
        "symbols_read": int(ohlc["symbol"].nunique()) if not ohlc.empty else 0,
        "query_error_class": query_error,
        "db_config_values_printed": False,
        "db_credentials_stored": False,
    }

    write_outputs(config, ohlc, coverage, query_audit, config_audit, safety, pd.DataFrame(issues), run_meta)
    return SqlMarketDataReadonlyResult(
        ohlc=ohlc,
        source_coverage=coverage,
        query_audit=query_audit,
        config_audit=config_audit,
        safety_audit=safety,
        issues_or_risks=pd.DataFrame(issues),
        run_meta=run_meta,
    )


def default_connection_factory(db_config: dict[str, Any]) -> Any:
    """Create a MySQL connection; kept injectable for tests."""
    import mysql.connector

    return mysql.connector.connect(**db_config)


def fetch_dataframe(connection: Any, query: str, params: tuple[Any, ...]) -> pd.DataFrame:
    cursor = connection.cursor()
    try:
        cursor.execute(query, params)
        rows = cursor.fetchall()
        columns = [col[0] for col in cursor.description] if cursor.description else []
    finally:
        cursor.close()
    return pd.DataFrame(rows, columns=columns)


def close_connection(connection: Any) -> None:
    if connection is None:
        return
    close = getattr(connection, "close", None)
    if callable(close):
        close()


def fetch_market_ohlc(connection: Any, config: SqlMarketDataReadonlyConfig) -> pd.DataFrame:
    symbols_query, symbols_params = build_enabled_symbols_query(config)
    symbols = fetch_dataframe(connection, symbols_query, symbols_params)
    if symbols.empty:
        return empty_ohlc_frame()
    pair_query = build_pair_ohlc_query()
    frames: list[pd.DataFrame] = []
    for _, row in symbols.iterrows():
        symbol = str(row["symbol"])
        for timeframe in config.timeframes:
            part = fetch_dataframe(connection, pair_query, (symbol, timeframe, int(config.bars_per_pair)))
            if not part.empty:
                frames.append(part)
    if not frames:
        return empty_ohlc_frame()
    return pd.concat(frames, ignore_index=True)


def build_enabled_symbols_query(config: SqlMarketDataReadonlyConfig) -> tuple[str, tuple[Any, ...]]:
    group_filter = ""
    params: list[Any] = []
    if config.groups:
        group_placeholders = ", ".join(["%s"] * len(config.groups))
        group_filter = f"AND sc.`group` IN ({group_placeholders})"
        params.extend(config.groups)
    query = f"""
        SELECT
            sc.symbol,
            sc.`group` AS market_group
        FROM symbol_control sc
        WHERE sc.enabled = TRUE
          {group_filter}
        ORDER BY sc.symbol ASC
    """
    return query, tuple(params)


def build_pair_ohlc_query() -> str:
    return """
        SELECT
            sc.`group` AS market_group,
            pd.symbol,
            pd.timeframe,
            pd.time AS timestamp,
            pd.open,
            pd.high,
            pd.low,
            pd.close,
            pd.tick_volume,
            pd.spread,
            pd.real_volume
        FROM price_data pd
        INNER JOIN symbol_control sc
            ON sc.symbol = pd.symbol
        WHERE sc.enabled = TRUE
          AND pd.symbol = %s
          AND pd.timeframe = %s
        ORDER BY pd.time DESC
        LIMIT %s
    """


def is_select_only_query(query: str) -> bool:
    compact = " ".join(query.strip().split())
    if not compact.lower().startswith("select "):
        return False
    if ";" in compact:
        return False
    return FORBIDDEN_SQL_TOKENS.search(compact) is None


def normalize_ohlc_frame(frame: pd.DataFrame) -> pd.DataFrame:
    if frame.empty:
        return empty_ohlc_frame()
    work = frame.copy()
    for column in REQUIRED_OHLC_COLUMNS:
        if column not in work.columns:
            work[column] = None
    work["timestamp"] = pd.to_datetime(work["timestamp"], errors="coerce")
    for column in ("open", "high", "low", "close", "tick_volume", "spread", "real_volume"):
        work[column] = pd.to_numeric(work[column], errors="coerce")
    work = work.dropna(subset=["symbol", "timeframe", "timestamp", "open", "high", "low", "close"])
    work["symbol"] = work["symbol"].astype(str)
    work["timeframe"] = work["timeframe"].astype(str)
    work["market_group"] = work["market_group"].fillna("not_available").astype(str)
    return work.reindex(columns=REQUIRED_OHLC_COLUMNS).sort_values(["symbol", "timeframe", "timestamp"]).reset_index(drop=True)


def empty_ohlc_frame() -> pd.DataFrame:
    return pd.DataFrame(columns=REQUIRED_OHLC_COLUMNS)


def build_config_audit(
    db_config: dict[str, Any],
    config_source: str,
    config: SqlMarketDataReadonlyConfig,
) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"item": "host_is_local", "value": is_local_host(str(db_config.get("host"))), "status": "passed" if is_local_host(str(db_config.get("host"))) else "blocked"},
            {"item": "port_present", "value": bool(db_config.get("port")), "status": "passed"},
            {"item": "user_present", "value": bool(db_config.get("user")), "status": "passed" if db_config.get("user") else "warning"},
            {"item": "database_present", "value": bool(db_config.get("database")), "status": "passed" if db_config.get("database") else "warning"},
            {"item": "password_present", "value": bool(db_config.get("password")), "status": "presence_only"},
            {"item": "config_source", "value": sanitize_config_source(config_source), "status": "presence_only"},
            {"item": "allow_nonlocal_db", "value": bool(config.allow_nonlocal_db), "status": "configured"},
        ]
    )


def build_query_audit(symbols_query: str, pair_query: str, symbols_params: tuple[Any, ...], config: SqlMarketDataReadonlyConfig) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"check": "symbols_query_select_only", "status": "passed" if is_select_only_query(symbols_query) else "blocked", "value": is_select_only_query(symbols_query)},
            {"check": "pair_query_select_only", "status": "passed" if is_select_only_query(pair_query) else "blocked", "value": is_select_only_query(pair_query)},
            {"check": "query_uses_params", "status": "passed", "value": True},
            {"check": "query_strategy", "status": "configured", "value": "enabled_symbols_then_pair_limited_selects"},
            {"check": "timeframes_requested", "status": "configured", "value": "|".join(config.timeframes)},
            {"check": "groups_requested_count", "status": "configured", "value": len(config.groups)},
            {"check": "bars_per_pair", "status": "configured", "value": int(config.bars_per_pair)},
            {"check": "symbol_query_param_count", "status": "configured", "value": len(symbols_params)},
            {"check": "query_text_stored", "status": "sanitized", "value": False},
        ]
    )


def build_safety_audit(symbols_query: str, pair_query: str) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"check": "select_only_guard", "status": "passed" if is_select_only_query(symbols_query) and is_select_only_query(pair_query) else "blocked", "value": is_select_only_query(symbols_query) and is_select_only_query(pair_query)},
            {"check": "sql_real_written", "status": "passed", "value": False},
            {"check": "ddl_executed", "status": "passed", "value": False},
            {"check": "mt5_connected", "status": "passed", "value": False},
            {"check": "telegram_connected", "status": "passed", "value": False},
            {"check": "credentials_printed", "status": "passed", "value": False},
            {"check": "credentials_stored", "status": "passed", "value": False},
        ]
    )


def source_coverage_audit(ohlc: pd.DataFrame, config: SqlMarketDataReadonlyConfig) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for timeframe in config.timeframes:
        part = ohlc[ohlc["timeframe"].astype(str) == timeframe] if not ohlc.empty else ohlc
        rows.append(
            {
                "timeframe": timeframe,
                "rows": int(len(part)),
                "symbols": int(part["symbol"].nunique()) if not part.empty else 0,
                "first_timestamp": timestamp_text(part["timestamp"].min()) if not part.empty else "",
                "last_timestamp": timestamp_text(part["timestamp"].max()) if not part.empty else "",
                "status": "available" if not part.empty else "missing",
            }
        )
    return pd.DataFrame(rows)


def write_outputs(
    config: SqlMarketDataReadonlyConfig,
    ohlc: pd.DataFrame,
    coverage: pd.DataFrame,
    query_audit: pd.DataFrame,
    config_audit: pd.DataFrame,
    safety: pd.DataFrame,
    issues: pd.DataFrame,
    run_meta: dict[str, Any],
) -> None:
    output = config.output_dir
    tables = output / "tables"
    output.mkdir(parents=True, exist_ok=True)
    tables.mkdir(parents=True, exist_ok=True)
    ohlc.to_csv(output / "ohlc_mtf.csv", index=False)
    (output / "ohlc_mtf.json").write_text(ohlc.to_json(orient="records", indent=2, force_ascii=False), encoding="utf-8")
    write_csv(tables / "source_coverage_audit.csv", coverage.to_dict(orient="records"))
    write_csv(tables / "sql_readonly_query_audit.csv", query_audit.to_dict(orient="records"))
    write_csv(tables / "sql_readonly_config_audit.csv", config_audit.to_dict(orient="records"))
    write_csv(tables / "sql_readonly_safety_audit.csv", safety.to_dict(orient="records"))
    write_csv(tables / "issues_or_risks.csv", issues.to_dict(orient="records"))
    (output / "run_meta.json").write_text(json.dumps(run_meta, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    (output / "SQL_MARKET_DATA_READONLY_V1.md").write_text(render_report(run_meta), encoding="utf-8")


def render_report(run_meta: dict[str, Any]) -> str:
    return f"""# SQL Market Data Read-only V1

Fecha: 2026-05-31

Decision: `{run_meta['decision']}`.

## Resultado

Extractor read-only para alimentar el radar de mercado con OHLC M15/H1/H4/D1.
La salida principal es `ohlc_mtf.csv`, que despues consume el dashboard como
artifact local.

## Seguridad

- SQL read ejecutado: `{run_meta['sql_real_read']}`.
- SQL write ejecutado: `False`.
- DDL ejecutado: `False`.
- DB conectada durante extraccion: `{run_meta['db_connected']}`.
- Credenciales impresas/guardadas: `False`.
- MT5/Telegram: `False`.

## Datos

- filas leidas: {run_meta['rows_read']}
- simbolos leidos: {run_meta['symbols_read']}
- timeframes: {', '.join(run_meta['timeframes'])}
- velas maximas por simbolo/timeframe: {run_meta['bars_per_pair']}

## Uso

```powershell
python -m trading_center.sql_market_data_readonly --output-dir artifacts/tfg/trading_center_sql_market_data_readonly_v1_2026-05-31
```
"""


def decide_result(issues: list[dict[str, Any]], ohlc: pd.DataFrame) -> str:
    if any(row["severity"] == "high" for row in issues):
        return "sql_market_data_readonly_blocked_by_safety"
    if ohlc.empty:
        return "sql_market_data_readonly_no_rows"
    return "sql_market_data_readonly_ready_for_market_radar"


def issue(issue_id: str, severity: str, status: str, description: str, mitigation: str) -> dict[str, Any]:
    return {
        "issue_id": issue_id,
        "severity": severity,
        "status": status,
        "description": description,
        "mitigation": mitigation,
    }


def sanitize_config_source(config_source: str) -> str:
    if not config_source:
        return "not_available"
    parts = []
    for item in str(config_source).split(";"):
        key = item.split(":", 1)[0].strip()
        source = item.split(":", 1)[1].strip() if ":" in item else "configured"
        parts.append(f"{key}:{source}")
    return "; ".join(parts)


def is_local_host(host: str) -> bool:
    return host.strip().lower() in LOCAL_HOSTS


def timestamp_text(value: Any) -> str:
    if value in (None, ""):
        return ""
    if pd.isna(value):
        return ""
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    return str(value)


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def parse_csv_tuple(value: str | None, default: tuple[str, ...]) -> tuple[str, ...]:
    if value is None:
        return default
    return tuple(item.strip() for item in value.split(",") if item.strip())


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract read-only SQL OHLC artifacts for the Trading Center market radar.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--timeframes", default=",".join(DEFAULT_TIMEFRAMES))
    parser.add_argument("--groups", default="")
    parser.add_argument("--bars-per-pair", type=int, default=DEFAULT_BARS_PER_PAIR)
    parser.add_argument("--allow-nonlocal-db", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    extract_sql_market_data(
        SqlMarketDataReadonlyConfig(
            output_dir=args.output_dir,
            timeframes=parse_csv_tuple(args.timeframes, DEFAULT_TIMEFRAMES),
            groups=parse_csv_tuple(args.groups, DEFAULT_GROUPS),
            bars_per_pair=args.bars_per_pair,
            allow_nonlocal_db=args.allow_nonlocal_db,
        )
    )


if __name__ == "__main__":
    main()
